"""
Seed catalog of ~50 common strength exercises.

Muscle groups are normalized to: chest, back, shoulders, biceps, triceps,
quads, hamstrings, glutes, calves, core, traps, forearms.

Movement patterns: squat, hinge, push_horizontal, push_vertical,
pull_horizontal, pull_vertical, lunge, carry, core, isolation.
"""

from typing import Any, Dict, List

EXERCISES: List[Dict[str, Any]] = [
    # --- Squat / quad-dominant ---
    {
        "name": "Back Squat",
        "primary_muscle": "quads",
        "secondary_muscles": ["glutes", "core", "hamstrings"],
        "equipment": "barbell",
        "movement_pattern": "squat",
    },
    {
        "name": "Front Squat",
        "primary_muscle": "quads",
        "secondary_muscles": ["glutes", "core"],
        "equipment": "barbell",
        "movement_pattern": "squat",
    },
    {
        "name": "Goblet Squat",
        "primary_muscle": "quads",
        "secondary_muscles": ["glutes", "core"],
        "equipment": "dumbbell",
        "movement_pattern": "squat",
    },
    {
        "name": "Leg Press",
        "primary_muscle": "quads",
        "secondary_muscles": ["glutes", "hamstrings"],
        "equipment": "machine",
        "movement_pattern": "squat",
    },
    {
        "name": "Bulgarian Split Squat",
        "primary_muscle": "quads",
        "secondary_muscles": ["glutes", "hamstrings"],
        "equipment": "dumbbell",
        "movement_pattern": "lunge",
    },
    {
        "name": "Walking Lunge",
        "primary_muscle": "quads",
        "secondary_muscles": ["glutes", "hamstrings"],
        "equipment": "dumbbell",
        "movement_pattern": "lunge",
    },
    {
        "name": "Leg Extension",
        "primary_muscle": "quads",
        "secondary_muscles": [],
        "equipment": "machine",
        "is_compound": False,
        "movement_pattern": "isolation",
    },
    # --- Hinge / posterior chain ---
    {
        "name": "Deadlift",
        "primary_muscle": "hamstrings",
        "secondary_muscles": ["glutes", "back", "core", "traps"],
        "equipment": "barbell",
        "movement_pattern": "hinge",
    },
    {
        "name": "Romanian Deadlift",
        "primary_muscle": "hamstrings",
        "secondary_muscles": ["glutes", "back"],
        "equipment": "barbell",
        "movement_pattern": "hinge",
    },
    {
        "name": "Dumbbell RDL",
        "primary_muscle": "hamstrings",
        "secondary_muscles": ["glutes", "back"],
        "equipment": "dumbbell",
        "movement_pattern": "hinge",
    },
    {
        "name": "Trap Bar Deadlift",
        "primary_muscle": "quads",
        "secondary_muscles": ["glutes", "hamstrings", "back", "traps"],
        "equipment": "barbell",
        "movement_pattern": "hinge",
    },
    {
        "name": "Hip Thrust",
        "primary_muscle": "glutes",
        "secondary_muscles": ["hamstrings", "core"],
        "equipment": "barbell",
        "movement_pattern": "hinge",
    },
    {
        "name": "Kettlebell Swing",
        "primary_muscle": "glutes",
        "secondary_muscles": ["hamstrings", "core", "back"],
        "equipment": "kettlebell",
        "movement_pattern": "hinge",
    },
    {
        "name": "Leg Curl",
        "primary_muscle": "hamstrings",
        "secondary_muscles": [],
        "equipment": "machine",
        "is_compound": False,
        "movement_pattern": "isolation",
    },
    {
        "name": "Good Morning",
        "primary_muscle": "hamstrings",
        "secondary_muscles": ["glutes", "back"],
        "equipment": "barbell",
        "movement_pattern": "hinge",
    },
    # --- Horizontal push ---
    {
        "name": "Bench Press",
        "primary_muscle": "chest",
        "secondary_muscles": ["triceps", "shoulders"],
        "equipment": "barbell",
        "movement_pattern": "push_horizontal",
    },
    {
        "name": "Incline Bench Press",
        "primary_muscle": "chest",
        "secondary_muscles": ["shoulders", "triceps"],
        "equipment": "barbell",
        "movement_pattern": "push_horizontal",
    },
    {
        "name": "Dumbbell Bench Press",
        "primary_muscle": "chest",
        "secondary_muscles": ["triceps", "shoulders"],
        "equipment": "dumbbell",
        "movement_pattern": "push_horizontal",
    },
    {
        "name": "Incline Dumbbell Press",
        "primary_muscle": "chest",
        "secondary_muscles": ["shoulders", "triceps"],
        "equipment": "dumbbell",
        "movement_pattern": "push_horizontal",
    },
    {
        "name": "Push-Up",
        "primary_muscle": "chest",
        "secondary_muscles": ["triceps", "shoulders", "core"],
        "equipment": "bodyweight",
        "movement_pattern": "push_horizontal",
    },
    {
        "name": "Dips",
        "primary_muscle": "chest",
        "secondary_muscles": ["triceps", "shoulders"],
        "equipment": "bodyweight",
        "movement_pattern": "push_horizontal",
    },
    {
        "name": "Cable Chest Fly",
        "primary_muscle": "chest",
        "secondary_muscles": ["shoulders"],
        "equipment": "cable",
        "is_compound": False,
        "movement_pattern": "isolation",
    },
    # --- Vertical push ---
    {
        "name": "Overhead Press",
        "primary_muscle": "shoulders",
        "secondary_muscles": ["triceps", "core"],
        "equipment": "barbell",
        "movement_pattern": "push_vertical",
    },
    {
        "name": "Dumbbell Shoulder Press",
        "primary_muscle": "shoulders",
        "secondary_muscles": ["triceps"],
        "equipment": "dumbbell",
        "movement_pattern": "push_vertical",
    },
    {
        "name": "Arnold Press",
        "primary_muscle": "shoulders",
        "secondary_muscles": ["triceps"],
        "equipment": "dumbbell",
        "movement_pattern": "push_vertical",
    },
    {
        "name": "Lateral Raise",
        "primary_muscle": "shoulders",
        "secondary_muscles": [],
        "equipment": "dumbbell",
        "is_compound": False,
        "movement_pattern": "isolation",
    },
    {
        "name": "Rear Delt Fly",
        "primary_muscle": "shoulders",
        "secondary_muscles": ["back"],
        "equipment": "dumbbell",
        "is_compound": False,
        "movement_pattern": "isolation",
    },
    # --- Horizontal pull ---
    {
        "name": "Barbell Row",
        "primary_muscle": "back",
        "secondary_muscles": ["biceps", "traps"],
        "equipment": "barbell",
        "movement_pattern": "pull_horizontal",
    },
    {
        "name": "Dumbbell Row",
        "primary_muscle": "back",
        "secondary_muscles": ["biceps"],
        "equipment": "dumbbell",
        "movement_pattern": "pull_horizontal",
    },
    {
        "name": "Seated Cable Row",
        "primary_muscle": "back",
        "secondary_muscles": ["biceps", "traps"],
        "equipment": "cable",
        "movement_pattern": "pull_horizontal",
    },
    {
        "name": "T-Bar Row",
        "primary_muscle": "back",
        "secondary_muscles": ["biceps", "traps"],
        "equipment": "barbell",
        "movement_pattern": "pull_horizontal",
    },
    {
        "name": "Chest-Supported Row",
        "primary_muscle": "back",
        "secondary_muscles": ["biceps"],
        "equipment": "machine",
        "movement_pattern": "pull_horizontal",
    },
    {
        "name": "Face Pull",
        "primary_muscle": "shoulders",
        "secondary_muscles": ["back", "traps"],
        "equipment": "cable",
        "is_compound": False,
        "movement_pattern": "isolation",
    },
    # --- Vertical pull ---
    {
        "name": "Pull-Up",
        "primary_muscle": "back",
        "secondary_muscles": ["biceps", "forearms"],
        "equipment": "bodyweight",
        "movement_pattern": "pull_vertical",
    },
    {
        "name": "Chin-Up",
        "primary_muscle": "back",
        "secondary_muscles": ["biceps", "forearms"],
        "equipment": "bodyweight",
        "movement_pattern": "pull_vertical",
    },
    {
        "name": "Lat Pulldown",
        "primary_muscle": "back",
        "secondary_muscles": ["biceps"],
        "equipment": "cable",
        "movement_pattern": "pull_vertical",
    },
    # --- Arms ---
    {
        "name": "Barbell Curl",
        "primary_muscle": "biceps",
        "secondary_muscles": ["forearms"],
        "equipment": "barbell",
        "is_compound": False,
        "movement_pattern": "isolation",
    },
    {
        "name": "Dumbbell Curl",
        "primary_muscle": "biceps",
        "secondary_muscles": ["forearms"],
        "equipment": "dumbbell",
        "is_compound": False,
        "movement_pattern": "isolation",
    },
    {
        "name": "Hammer Curl",
        "primary_muscle": "biceps",
        "secondary_muscles": ["forearms"],
        "equipment": "dumbbell",
        "is_compound": False,
        "movement_pattern": "isolation",
    },
    {
        "name": "Preacher Curl",
        "primary_muscle": "biceps",
        "secondary_muscles": [],
        "equipment": "machine",
        "is_compound": False,
        "movement_pattern": "isolation",
    },
    {
        "name": "Tricep Pushdown",
        "primary_muscle": "triceps",
        "secondary_muscles": [],
        "equipment": "cable",
        "is_compound": False,
        "movement_pattern": "isolation",
    },
    {
        "name": "Skull Crusher",
        "primary_muscle": "triceps",
        "secondary_muscles": [],
        "equipment": "barbell",
        "is_compound": False,
        "movement_pattern": "isolation",
    },
    {
        "name": "Overhead Tricep Extension",
        "primary_muscle": "triceps",
        "secondary_muscles": [],
        "equipment": "dumbbell",
        "is_compound": False,
        "movement_pattern": "isolation",
    },
    # --- Core ---
    {
        "name": "Plank",
        "primary_muscle": "core",
        "secondary_muscles": ["shoulders"],
        "equipment": "bodyweight",
        "movement_pattern": "core",
    },
    {
        "name": "Hanging Leg Raise",
        "primary_muscle": "core",
        "secondary_muscles": [],
        "equipment": "bodyweight",
        "is_compound": False,
        "movement_pattern": "core",
    },
    {
        "name": "Cable Crunch",
        "primary_muscle": "core",
        "secondary_muscles": [],
        "equipment": "cable",
        "is_compound": False,
        "movement_pattern": "core",
    },
    {
        "name": "Ab Wheel Rollout",
        "primary_muscle": "core",
        "secondary_muscles": ["shoulders"],
        "equipment": "bodyweight",
        "movement_pattern": "core",
    },
    {
        "name": "Russian Twist",
        "primary_muscle": "core",
        "secondary_muscles": [],
        "equipment": "dumbbell",
        "is_compound": False,
        "movement_pattern": "core",
    },
    # --- Calves / misc ---
    {
        "name": "Standing Calf Raise",
        "primary_muscle": "calves",
        "secondary_muscles": [],
        "equipment": "machine",
        "is_compound": False,
        "movement_pattern": "isolation",
    },
    {
        "name": "Seated Calf Raise",
        "primary_muscle": "calves",
        "secondary_muscles": [],
        "equipment": "machine",
        "is_compound": False,
        "movement_pattern": "isolation",
    },
    {
        "name": "Farmer's Carry",
        "primary_muscle": "traps",
        "secondary_muscles": ["forearms", "core", "back"],
        "equipment": "dumbbell",
        "movement_pattern": "carry",
    },
    {
        "name": "Shrug",
        "primary_muscle": "traps",
        "secondary_muscles": ["forearms"],
        "equipment": "barbell",
        "is_compound": False,
        "movement_pattern": "isolation",
    },
]
